[build.environment]
NODE_VERSION = "20"

[build]
publish = "dist"
command = "pnpm build"

[[redirects]]
from = "/subtyping-in-typescript/*"
to = "/subtyping-in-typescript/index.html"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
